"""add soft delete to expenses

Revision ID: 0e49d4cdbb74
Revises: 9d9fdd922b5c
Create Date: 2026-07-15 02:03:09.132548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e49d4cdbb74'
down_revision: Union[str, Sequence[str], None] = '9d9fdd922b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'deleted_at')
    # ### end Alembic commands ###
