"""add income table

Revision ID: c00dec467954
Revises: 0e49d4cdbb74
Create Date: 2026-07-15 02:15:36.587865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00dec467954'
down_revision: Union[str, Sequence[str], None] = '0e49d4cdbb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_account_id'), 'income', ['account_id'], unique=False)
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    op.create_index(op.f('ix_income_income_date'), 'income', ['income_date'], unique=False)
    op.create_index(op.f('ix_income_user_id'), 'income', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_user_id'), table_name='income')
    op.drop_index(op.f('ix_income_income_date'), table_name='income')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_index(op.f('ix_income_account_id'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
